[pytest]
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::sklearn.exceptions.InconsistentVersionWarning
    ignore:X does not have valid feature names, but KMeans was fitted with feature names:UserWarning
